//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrder.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Newtonsoft.Json;

    public partial class BaseCode : ModelBase<BaseCode>, IModel<BaseCode>
    {
        // Primitive properties
        [Display(Name = "±àÂë")]
        public string Code { get; set; }
        [Display(Name = "Ãû³Æ")]
        public string Name { get; set; }
        public string CodeType { get; set; }
        [Display(Name = "±¸×¢")]
        public string Memo { get; set; }

        // Navigation properties
        [JsonIgnore]
        public virtual ICollection<Product> Products { get; set; }
    }
}
