//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace OnlineOrder.Website.Models
{
    public partial class BaseCode : ModelBase<BaseCode>, IModel<BaseCode>
    {
        public BaseCode()
        {
            this.Products = new HashSet<Product>();
        }       
        public string Code { get; set; }
        public string Name { get; set; }
        public string CodeType { get; set; }
        public string Memo { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
    
}
