//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrder.Website.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category : ModelBase<Category>, IModel<Category>
    {
        // Primitive properties    
        [Display(Name = "编码")]
        [Required(AllowEmptyStrings = false)]
        public string Code { get; set; }
        [Display(Name = "名称")]
        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }
        [Display(Name = "类别信息")]
        public Nullable<int> ParentId { get; set; }
        [Display(Name = "毛利率")]
        public Nullable<decimal> ProfitRate { get; set; }

        // Navigation properties
        [ForeignKey("ParentId")]
        [JsonIgnore]
        public virtual ICollection<Category> Children { get; set; }
        [JsonIgnore]
        public virtual Category Parent { get; set; }
        [JsonIgnore]
        public virtual ICollection<Product> Products { get; set; }

        /// <summary>
        /// 有无孩子节点
        /// </summary>
        public bool hasChild
        {
            get
            {
                return this.Children != null && this.Children.Count > 0;
            }
        }
    
    }
}
