//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace OnlineOrder.Website.Models
{
    public partial class Customer : ModelBase<Customer>, IModel<Customer>
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.Receipts = new HashSet<Receipt>();
        }
        [Display(Name = "±àÂë")]
        public string Code { get; set; }
        [Display(Name = "Ãû³Æ")]
        public string Name { get; set; }
        [Display(Name = "ÕÛ¿Û")]
        public Nullable<decimal> Discount { get; set; }
        [Display(Name = "±¸×¢")]
        public string Memo { get; set; }
        [JsonIgnore]
        public virtual ICollection<Order> Orders { get; set; }
        [JsonIgnore]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
    
}
