//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace OnlineOrder.Website.Models
{
    public partial class Logistic : ModelBase<Logistic>, IModel<Logistic>
    {
        public Logistic()
        {
            this.SendOrders = new HashSet<SendOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Linkman { get; set; }
        public string Tel { get; set; }
        public string WebSite { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<SendOrder> SendOrders { get; set; }
    }
    
}
