//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OnlineOrder.Website.Models
{
    public partial class Order : SheetModelBase<Order>, ISheetModel<Order>
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        [Display(Name = "付款日期")]
        public Nullable<System.DateTime> PayDate { get; set; }
        [Display(Name = "金额")]
        public Nullable<decimal> Amount { get; set; }       
        [Display(Name = "状态")]
        public string Status { get; set; }       
        [Display(Name = "客户")]
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual User User { get; set; }
    }
    
}
