//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OnlineOrder.Website.Models
{
    public partial class Product : ModelBase<Product>, IModel<Product>
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.SendOrderDetails = new HashSet<SendOrderDetail>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
       [Display(Name = "编码")]
        public string Code { get; set; }
        [Display(Name = "品名")]
        public string Name { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> BrandId { get; set; }
        [Display(Name = "成本价")]
        public Nullable<decimal> CostPrice { get; set; }
        [Display(Name = "售价")]
        public Nullable<decimal> SalePrice { get; set; }
        [Display(Name = "库存数量")]
        public Nullable<decimal> StockQty { get; set; }
        [Display(Name = "描述")]
        public string Description { get; set; }
        [Display(Name = "状态")]
        public string Status { get; set; }
        [Display(Name = "备注")]
        public string Memo { get; set; }
        public Nullable<int> OperId { get; set; }
        [Display(Name = "制单日期")]
        public Nullable<System.DateTime> OperDate { get; set; }
        public Nullable<int> ModifyId { get; set; }
        [Display(Name = "修改日期")]
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual BaseCode BaseCode { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User Oper { get; set; }
        public virtual User Modify { get; set; }
        public virtual ICollection<SendOrderDetail> SendOrderDetails { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
    
}
