//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace OnlineOrder.Website.Models
{
    public partial class Receipt : ModelBase<Receipt>, IModel<Receipt>
    {
        public Receipt()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Linkman { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Memo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
    
}
