//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace OnlineOrder.Website.Models
{
    public partial class SendOrder : ModelBase<SendOrder>, IModel<SendOrder>
    {
        public SendOrder()
        {
            this.SendOrderDetails = new HashSet<SendOrderDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> LogisticId { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ApproveFlag { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> OperId { get; set; }
        public Nullable<System.DateTime> OperDate { get; set; }
    
        public virtual Logistic Logistic { get; set; }
        public virtual ICollection<SendOrderDetail> SendOrderDetails { get; set; }
    }
    
}
