//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace OnlineOrder.Website.Models
{
    public partial class User : ModelBase<User>, IModel<User>
    {
        public User()
        {
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
        }
        [Display(Name = "±àÂë")]
        public string Code { get; set; }
        [Display(Name = "Ãû³Æ")]
        public string Name { get; set; }
        [Display(Name = "ÃÜÂë")]
        public string Password { get; set; }
        [Display(Name ="ÓÊ¼þ")]
        public string Email { get; set; }
        public Nullable<int> CustomerId { get; set; }       
        [JsonIgnore]
        public virtual ICollection<Order> Orders { get; set; }
        [JsonIgnore]
        public virtual ICollection<Product> Products { get; set; }
        [JsonIgnore]
        public virtual ICollection<Product> Products1 { get; set; }
    }
    
}
