//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrder.Website.Models
{
    using System;
    using System.Data.Entity;
    
    public partial class OnlineOrderDb : DbContext
    {
        public OnlineOrderDb()
            : base("name=OnlineOrderDb")
        {
    		Configuration.AutoDetectChangesEnabled = false;
        }
    
        public virtual void Commit()
        {
             base.SaveChanges();
        }
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
             //TODO:以下代码用于开启级联删除，但是针对自关联表只能删除第一层子数据
             //modelBuilder.Entity<Product>()
             //    .HasOptional(e => e.ProductBarcodes)
             //    .WithMany(e => e.ProductBarcodes)
             //    .WillCascadeOnDelete();
        }
    
        public DbSet<BaseCode> BaseCodes { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Logistic> Logistics { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Receipt> Receipts { get; set; }
        public DbSet<SendOrderDetail> SendOrderDetails { get; set; }
        public DbSet<SendOrder> SendOrders { get; set; }
        public DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
